services:
  olx-notifier-bot:
    image: ghcr.io/anotherk1t/olxpl_listingscraper:latest
    container_name: olx-notifier
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data